name: Build & Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Build and test, Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install poetry
        shell: bash
        run: pip install poetry

      - name: Install project
        run: |
          poetry install

      - name: Test
        run: |
          poetry run pytest

      - name: Get version
        id: get_version
        run: |
          echo "version=$(poetry version --short)" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          poetry build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openxes_cli_py-py${{ matrix.python-version }}-${{ steps.get_version.outputs.version }}
          path: dist

      - name: Assign repository tag
        run: |
          git tag ${{ steps.get_version.outputs.version }}
          git push --tags

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/openxes_cli_py-${{ steps.get_version.outputs.version }}-py${{ matrix.python-version }}.whl
            dist/openxes_cli_py-${{ steps.get_version.outputs.version }}-py${{ matrix.python-version }}.tar.gz
          tag_name: ${{ steps.get_version.outputs.version }}
          body: |
            # OpenXES-CLI Python
            
            These are Python bindings for the [OpenXES-CLI](https://github.com/AutomatedProcessImprovement/openxes-cli) application.
            
            ## Changelog
            $(git log --format="%h %s" $(git describe --tags --abbrev=0)..HEAD)